app/core/urls.py
from django.urls import path

from .views import *


app_name = 'core'

urlpatterns = [
    path('', TestListView.as_view(), name='test_list'),
    path('tests/test_<int:test_id>/question_<int:question_id>', question_view, name='questions'),
    path('result/result_of_test_<int:test_id>', test_result, name='test_result'),
    path('result_list', AllResultsView.as_view(), name='result_list')
]

app/test_surveys/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import path, include, reverse_lazy
from django.views.generic import CreateView


urlpatterns = [
    path('', include('core.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('core:test_list'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

app/core/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Test(models.Model):
    title = models.CharField(
        max_length=50,
        unique=True
    )
    is_active = models.BooleanField(
        default=False
    )
    description = models.CharField(
        max_length=300,
    )

    def __str__(self):
        return self.title


class Result(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.DO_NOTHING,
    )
    is_finished = models.BooleanField(default=False)
    test = models.ForeignKey(
        to=Test,
        on_delete=models.DO_NOTHING
    )
    total_result = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class Question(models.Model):
    test = models.ForeignKey(
        to=Test,
        on_delete=models.DO_NOTHING
    )
    text = models.CharField(
        max_length=250,
        verbose_name="Text",
        unique=True
    )

    is_active = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(
        to=Question,
        on_delete=models.DO_NOTHING,
        verbose_name='Question',
    )
    text = models.CharField(
        max_length=50,
        verbose_name='Text',
    )
    is_right = models.BooleanField()
    lock_other = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Answer(models.Model):

    result = models.ForeignKey(
        to=Result,
        on_delete=models.DO_NOTHING,
    )

    question = models.ForeignKey(
        to='Question',
        on_delete=models.DO_NOTHING,
    )
    is_right = models.BooleanField()
    choice = models.ForeignKey(
        to='Choice',
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.choice.text

app/core/forms.py
from django import forms
from .models import *


class TestForm(forms.ModelForm):
    def clean(self):
        is_active = self.data.get('is_active')
        if is_active:

            # Костыль, тк возникала ошибка при попытке сделать тест сразу активным при создании
            try:
                current_test = Test.objects.get(title=self.data['title'])
            except Test.DoesNotExist:
                raise forms.ValidationError({'is_active': 'Должен быть хотя бы один вопрос в тесте!'})

            questions = Question.objects.filter(test_id=current_test.id)
            if not questions:
                raise forms.ValidationError({'is_active': 'Должен быть хотя бы один вопрос в тесте!'})

    class Meta:
        model = Test
        fields = '__all__'


class QuestionForm(forms.ModelForm):
    def clean(self):
        is_active = self.data.get('is_active')
        if is_active:

            # Костыль, тк возникала ошибка при попытке сделать вопрос сразу активным при создании
            try:
                current_question = Question.objects.get(text=self.data['text'])
            except Question.DoesNotExist:
                raise forms.ValidationError({'text': 'Должен быть хотя бы один вариант ответа!'})

            choices = Choice.objects.filter(question_id=current_question.id)

            if not choices:
                raise forms.ValidationError({'text': 'Должен быть хотя бы один вариант ответа!'})

            have_answer = False
            right_answers = 0
            for choice in choices:
                if choice.is_right:
                    have_answer = True
                    right_answers += 1

            if right_answers == len(choices):
                raise forms.ValidationError({'is_active': 'Все ответы не могут быть правильными!'})

            if not have_answer:
                raise forms.ValidationError({'is_active': 'У вопроса нет правильного ответа!'})

    class Meta:
        model = Question
        fields = '__all__'


class ChoicesForm(forms.Form):
    choice_field = forms.ChoiceField(
            choices=(),
            label=False,
            widget=forms.Select(attrs={
                'style': 'border-color: white; outline:none; width: 140px'
            })
        )

    def __init__(self, question_id):
        super(ChoicesForm, self).__init__(question_id)
        choices = list(Choice.objects.filter(question_id=question_id))
        for i in choices:
            self.fields['choices_fields'] = choices

app/core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import *
from .forms import ChoicesForm


User = get_user_model()
# TODO: После выбора ответа, ответ сохраняется, но не отображается в форме.


class TestListView(LoginRequiredMixin, ListView):
    """ View-класс для главной страницы с тестами. """
    model = Test
    ordering = 'id'
    paginate_by = 50


class AllResultsView(LoginRequiredMixin, ListView):
    """ View-класс для главной страницы с тестами. """
    model = Result
    ordering = 'user'
    paginate_by = 50


@login_required
def question_view(request, test_id, question_id):
    """ View-функция для обработки каждого вопроса отдельно. """
    test = get_object_or_404(Test, pk=test_id)
    current_question = Question.objects.get(test_id=test_id, id=question_id)
    choices = Choice.objects.filter(question_id=question_id)
    choices_form = ChoicesForm(question_id)
    if request.method == 'POST':
        # Если есть незавершенная попытка у пользователя с конкретным тестом, то переопределяем в нем данные
        # Если незавершенной попытки нет, то создаем новую.
        result = Result.objects.get_or_create(
            test=test,
            user=request.user,
            is_finished=False,
        )[0]
        choice_number = request.POST.get('choice')
        # Проверка на наличие выбора.
        if choice_number:
            choice_number = int(choice_number)
            # Если уже создавался объект Answer в этой попытке, то обновляем выбор
            # Если еще не давался ответ на вопрос, то создаем объект Answer
            selected_choice = Choice.objects.get(id=choice_number)
            answer = Answer.objects.update_or_create(
                result=result,
                question=current_question,
                defaults={
                    'choice': selected_choice,
                    'is_right': selected_choice.is_right
                }
            )

    context = {
        'test': test,
        'question': current_question,
        'choices': choices,
        'choices_form': choices_form,
    }
    return render(request, 'core/question.html', context)


@login_required
def test_result(request, test_id):
    result = get_object_or_404(
        Result,
        test_id=test_id,
        user=request.user,
        is_finished=False
    )
    answers = Answer.objects.filter(result_id=result.id)
    total_answers = len(answers)
    questions = Question.objects.filter(test_id=test_id, is_active=True)
    if total_answers != len(questions):
        for question in questions:
            for answer in answers:
                if answer.question_id == question.id:
                    break
            else:
                return question_view(request, result.test_id, question.id)

    right_answers = answers.filter(is_right=True)
    total_right_answers = len(right_answers)
    percent = int((total_right_answers/total_answers) * 100)
    context = {
        'total_answers': total_answers,
        'total_right_answers': total_right_answers,
        'percent': percent,
    }
    result.total_result = percent
    result.is_finished = True
    result.save()
    return render(request, 'core/result.html', context)

app/templates/core/question.html
{% extends 'base.html' %}
{% load tags %}
{% block content %}
    {% if question.is_active %}
    <article>
      <ul>
        <li>
          Название: {{ question.text }}
          <br>
        </li>
    <ul>
    <form method="post">
        {% csrf_token %}
        {% for choice in choices_form.fields.choices_fields  %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br />
        {% endfor %}
        <button class="add" role="button" type="submit">
            <span style="right: -20%;">Ответить</span>
        </button>
    </form>
    </ul>
    </ul>
    </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endif %}
    {% if test.id|get_previous_question:question.id %}
        <a href="{% url 'core:questions' test.id test.id|get_previous_question:question.id %}">Предыдущий вопрос</a>
        <br>
    {% endif %}
    {% if test.id|get_next_question:question.id %}
        <a href="{% url 'core:questions' test.id test.id|get_next_question:question.id %}">Следующий вопрос</a>
    {% else %}
        <a href="{% url 'core:test_result' test.id %}">Завершить тест</a>
    {% endif %}
{% endblock %}

app/templates/core/result.html
{% extends 'base.html' %}
{% block content %}
    Всего вопросов: {{ total_answers }}<br>
    Правильных ответов: {{ total_right_answers }}<br>
    Процент правильных ответов: {{ percent }}%
{% endblock %}

app/templates/core/result_list.html
{% extends 'base.html' %}
{% block content %}
{% for result in page_obj %}
    <article>
      <ul>
          <li>
          Пользователь: {{ result.user.username }}
          <br>
        </li>
        <li>
          Название: {{ result.id }}
          <br>
        </li>
        <li>
          Результат: {{ result.total_result }}
           <br>
        </li>
      </ul>

    </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}

app/templates/core/test_list.html
{% extends 'base.html' %}
{% block content %}
{% load tags %}
{% for test in page_obj %}
    {% if test.is_active %}
    <article>
      <ul>
        <li>
          Название: {{ test.title }}
          <br>
        </li>
        <li>
          Описание: {{ test.description }}
           <br>
        </li>
          <a href="{% url 'core:questions' test.id test.id|get_first_question %}">Пройти тест</a>
           <br>
      </ul>

    </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endif %}
    {% endfor %}
{#    {% include  'posts/includes/paginator.html' %}#}
{% endblock %}