app/core/urls.py
from django.urls import path

from .views import *


app_name = 'core'

urlpatterns = [
    path('', TestListView.as_view(), name='test_list'),
    path('tests/test_<int:test_id>/question_<int:question_id>', question_view, name='questions'),
    path('result/result_of_test_<int:test_id>', test_result, name='test_result'),
    path('result_list', AllResultsView.as_view(), name='result_list')
]

app/test_surveys/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import path, include, reverse_lazy
from django.views.generic import CreateView


urlpatterns = [
    path('', include('core.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('core:test_list'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

app/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">
      <p>
        <span style="color:red">TESTER</span><br>
        © {% now 'Y' %} Copyright
        <br> Aleksandr Sheshenin
      </p>
    </div>
</footer>

app/templates/includes/header.html
{% load static %}
<header>

    <nav class="navbar navbar-light" style="background-color: rgba(136,177,203,0.53)">
      <div class="container">
        <a class="navbar-brand" href="{% url 'core:test_list' %}">
          <img src="{% static 'img/icon.png' %}" width="35" height="35" class="d-inline-block align-top" alt="">
          <span style="color:#3946e7">Tester</span>
        </a>
        {% with request.resolver_match.view_name as view_name %}  
        <ul class="nav nav-pills">

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'core:result_list' %}">
                Все результаты
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'logout' %}">
                Выйти
            </a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'login' %}">
                Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'registration' %}active{% endif %}"
            href="{% url 'registration' %}"
            >
            Регистрация
            </a>
          </li>
          {% endif %}
        </ul>
        {% endwith %}
      </div>
    </nav>      
  </header>